### PR TITLE
Fix: Searching for outgoing invoice by InvoiceID

### LINKED ISSUE #197: Search for outgoing invoice not working correct
Video: fb2014 2016-06-23-search_outgoing_invoice.handbrake.mp4

### PR DESCRIPTION
**Pull request by Baxxx**
Closes #197

### CODE REVIEW

**Comment by sls-lnluksa** [comment]
@stoivo Currently we are printing error on invoice when we search by invoice id.
Do you see something useful in this or we should remove it?

**Comment by sls-lnluksa** [comment]
First round review: Nikola Lukovic (sls-lnluksa)
Final review with: @stoivo

**Comment by stoivo** [comment]
We should not print the validator errors of the invoices we are searching.

**Comment by sls-lnluksa** [comment]
First round review: Nikola Lukovic (sls-lnluksa)
Final review with: @stoivo

**Pull request merged**
