### PR TITLE
Fix create customer on outgoing invoice download page

### LINKED ISSUE #446: Create customer from outgoing invoice dowloaded from fakturabank
Video db: Lodo/2017-03-14_22-49-34_download_outgoing_invoices.zip

### PR DESCRIPTION
**Pull request by mladjo2505**
Closes #446 
Should be deployed with FB PR # 759

### CODE REVIEW

**Review by MrdjanStojimirovic — APPROVED** [review]

**Comment by stoivo** [comment]
```
When we want to download a invoice. 
Match it on firma id. 
  if there is one match
    if we have customer nr and it matches, it is awesome.
    if it doesn't match 
      print a waring message "Kundenummer i fakturabank(xxx) og lodo(yyy) er ulike" where we print "klar til bilagsføring ...""
      it is just a waring and we should be able to bookkeep this invoice, Use the accountplan where the Firma id matches
  else when there is several matches
    if one matches on customer nr use that one 
      print a waring message like "Kundenummer i fakturabank(xxx) og lodo(yyy) er like, fant flere match(xxx,yyy,zzz)"
    else no matches
      print a waring message like "Kundenummer i fakturabank(xxx) og lodo(yyy) er ulike, fant flere men ingen match(xxx,yyy,zzz)"

Every place where we refer to a accountplan make a link to the accountplan.
```

**Comment by stoivo** [comment]
Also look at the state on lodo2016, it looks like It jammed on a org nr

**Comment by stoivo** [comment]
We did a review, We will do testing on staging environment before i add my final review.

**Comment by hildegunn95** [comment]
Testet, all good, ready to be deployed.

**Review by stoivo — APPROVED** [review]

**Pull request merged**
