### PR TITLE
Revert "Revert "Postmotpost and reskontro voucher print fix""

### PR DESCRIPTION
**Pull request by stoivo**
Reverts dodoas/lodo#148

### CODE REVIEW

**Comment by MrdjanStojimirovic** [comment]
Reason for reverting:

sls-lnluksa commented 5 days ago
This branch needs to be tested by Hildegunn or someone who is using LODO, before it goes on live server.

**Comment by stoivo** [comment]
Need to watch and fix Video: Lodo/2016-05-12_09-35-43_improve_postmotpost.mp4

**Comment by stoivo** [comment]
We will talk about this on Friday 20th. 12:00 to 14:00.

**Comment by mladjo2505** [comment]
After discussion we agreed that we only need to fix one small thing to do with checkboxes on journal.edit page. If both are unchecked it should set match_by to 0.

**Comment by mladjo2505** [comment]
We tested (@sls-lnluksa and i). Everything works as it should. Only 2 last commits were new since others were reviewed before.

**Comment by stoivo** [comment]
I want to test this with Arnt a bit before I deploy this.

**Pull request merged**
