### PR TITLE
Add new report for altinn reported salaries

### LINKED ISSUE #70: New salary report for altinn reported salaries
Add a new report for salaries similar to report.terminoppgave only for altinn reported salaries.

### PR DESCRIPTION
**Pull request by mladjo2505**
Closes #70

### CODE REVIEW

**Comment by stoivo** [comment]
@mladjo2505 I would like if you could look at this and check that you think this make sense.

**Comment by stoivo** [comment]
modules/report/view/terminoppgave.php is just reindented.

**Comment by stoivo** [comment]
It did't work, fix it and open a new PR.

**Comment by mladjo2505** [comment]
@stoivo Either I do not know how this report is supposed to work or it works correctly on my machine.

**Comment by mladjo2505** [comment]
linked with #123

**Pull request merged**
