### PR TITLE
Fix and improve lock on tabbankaccount

### LINKED ISSUE #322: Lås on tabbankaccount not working
It seems like the "Lås"(lock) button does not have any function.
Should disable date and amount input fields.
The "Diff kontoutskrift-banktransaksjoner" has to be zero to be able to lock.
Save to DB who saved it and when

### PR DESCRIPTION
**Pull request by agvald**
Closes #322

### CODE REVIEW

**Comment by mladjo2505** [comment]
Make sure to rename the migration if it conflicts with another with the same number.

**Review by mladjo2505 — APPROVED** [review]
All good, ready for final review

**Comment by mladjo2505** [comment]
First round review: Mladen Drobnjaković (@mladjo2505)
Final review with: @stoivo

**Comment by agvald** [comment]
@agvald
keep in mind to possibly renumber migration before deploy

**Review by stoivo — APPROVED** [review]
Could have been two commit, but we want spend any time separating this.

**Pull request merged**
