### PR TITLE
Bp/pmp add indicator to automatically selected vouchers

### LINKED ISSUE #161: Add indicator to postmotpost vouchers
Add an indicator(colour on checkbox) to the automatically matched vouchers on post mot post page.

### PR DESCRIPTION
**Pull request by Baxxx**
Closes #161

### CODE REVIEW

**Comment by Baxxx** [comment]
Should be rebased after #149 is merged into master

**Comment by Baxxx** [comment]
Back to rework. Doesn't work as it should.

**Comment by Baxxx** [comment]
First round review by @sls-lnluksa. Only @stoivo is needed for final review.

**Comment by mladjo2505** [comment]
Rebased to master since #149 has been merged to master

**Pull request merged**
